- name: catalogue
  hosts: catalogue
  user: centos
  become: yes
  connection: ssh
  tasks:
  - name: need to disable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
  - name:  install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: add user
    ansible.builtin.user:
     name: roboshop
  - name: setup an app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download the application code to created app directory
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp

  - name: unzipping
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes
  - name: npm
    ansible.builtin.command: npm install
    args:
      chdir: /app
  - name: Setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: reload
    ansible.builtin.systemd_service:
     daemon_reload: true  

  # - name: enable catalogue
  #   ansible.builtin.service:
  #    name: catalogue
  #    enabled: true
  #    state: started 

  - name: copy mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install package
    ansible.builtin.package:
     name: mongodb-org-shell
     state:  present
  - name: 
    ansible.builtin.command: mongo --host mongodb.crobo.shop --quiet --eval 'db =db. getSiblingDB("catalogue"); db.products.count()'     
    register: product_count
  - name:  print the count
    ansible.builtin.debug:
      msg: "product count: {{product_count}}"
  # -  name: load catalogue data
  #    ansible.builtin.command: mongo --host mongodb.crobo.shop </app/schema/catalogue.js





          