- name: rabitmq
  hosts: rabbitmq
  user: centos
  become: yes
  tasks:
  - name: configure yum erlang repo
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name:   
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: 
    ansible.builtin.dnf:  
      name: rabbitmq-server
      state: present

  - name: 
    ansible.builtin.server:  
      name: rabbitmq-server
      state: restarted
      enabled: yes
 
  - name: 
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: 
    ansible.builtin.command:  rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" 


