# ansible-playbook -i inventory  -e ansible_user=centos -e ansible_password=DevOps321 shipping.yaml
- name:
  hosts: shipping
  become: yes
  vars:
    mysql_password: RoboShop@1
  tasks:
  - name: install maven
    dnf:
      name: maven
      state: present

  - name: 
    user:
      name: roboshop

  - name: 
    file:
      path: /app
      state: absent    

  - name: 
    file:
      path: /app
      state: directory

  - name:
    get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: 
    unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes


  - name:      
    command: mvn clean package
    args:
       chdir: /app

  - name: 
    command: mv target/shipping-1.0.jar shipping.jar  
    args: 
       chdir: /app

  - name:   
    copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name:    
    systemd_service:
      daemon_reload: true

  - name: 
    dnf:
      name: mysql
      state: present  

  - name:
    command: mysql -h mysql.crobo.shop -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA  WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: output
    debug:
      msg: "schema output: {{schema}}"  

  - name: load cities data
    shell: mysql -h mysql.crobo.shop -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
    when: schema.stdout != "1"   
          

  # -  name: 
  #    service:
  #      name: shipping
  #      enabled: yes
  #      state: started

  # - name: 
  #   dnf:
  #     name: mysql
  #     state: present





            