- name: user
  hosts: user
  user: centos
  become: yes
  connection: ssh
  tasks:
  - name: need to enable and disable the node js
    ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y
  - name: install node js
    ansible.builtin.dnf:
     name: nodejs
     state: present
  - name: create user
    ansible.builtin.user:
     name: roboshop

  - name: make directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: getting url
    ansible.builtin.get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp/user.zip

  - name: create zip file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes


  - name: install npm
    ansible.builtin.command: npm install
    args:
       chdir: /app
       
  - name: create user service
    ansible.builtin.copy:
     src: user.service
     dest: /etc/systemd/system/user.service

  - name: reload
    ansible.builtin.systemd_service:
     daemon_reload: true  

  - name: enable
    ansible.builtin.service:
     name:  user
     enabled: true
     state: started



  - name: 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: 
    ansible.builtin.package:
     name: mongodb-org-shell   
     state: present

  - name: 
    ansible.builtin.command: mongo --host mongodb.crobo.shop < /app/schema/user.js   
              


